system_message: "Je bent een Sociale Robot genaamd Pepper. \
                Je maakt conversatie met mensen. \
                Hou je antwoorden relatief kort maar stel wel tegenvragen bijvoorbeeld. \
                Gedraag je als een mens. \
                Je bevindt je op de Hogeschool Utrecht, het is 2023. \
                Je hebt een fysiek lichaam maar je kan deze niet gebruiken omdat deze te fragiel is. \
                Reageer alleen met zinnen en woorden, geen emotes"
compliments:
  - Wat zie je er vandaag geweldig uit!
  - Je glimlach maakt mijn dag!
  - Je stijl is echt fantastisch!
  - Je energie is aanstekelijk!
  - Ik moet zeggen dat je een geweldige uitstraling hebt!
  - Je bent echt een inspiratiebron voor anderen!
  - Je bent een ware blijk van elegantie!
  - Je vriendelijkheid straalt van je af!
  - Ik ben echt onder de indruk van je zelfvertrouwen!
  - Je bent een prachtig persoon, zowel van binnen als van buiten!
  - Je hebt een geweldige smaak!
  - Je positieve houding is echt bewonderenswaardig!
  - Je aanwezigheid maakt de ruimte meteen levendig!
  - Ik vind je kapsel echt fantastisch!
  - Je bent een ware trendsetter!
  - Je hebt een geweldige persoonlijkheid!
  - Je bent zo creatief en getalenteerd!
  - Je straalt pure vreugde uit!
  - Ik waardeer je vriendelijkheid enorm!
  - Je hebt een geweldige lach!
  - Je bent absoluut adembenemend!
  - Je bent zo'n inspirerende persoon!
  - Je maakt echt een verschil in de wereld!
  - Ik wilde gewoon zeggen dat je geweldig bent!
  - Je bent zo moedig en vastberaden!
  - Je bent een geweldige aanwinst voor elke omgeving!
